ElectoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("home.urls")),
                  path('', include("products.urls")),
                  path('', include("profile_users.urls")),
                  path('', include("contact.urls")),
                  path('cart/', include("cart.urls")),
                  path('accounts/', include("allauth.urls")),
                  # path('bankgateways/', az_bank_gateways_urls()),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('detail/', CartDetailView.as_view(),name="cart_detail"),
    path('add/<int:pk>', CartAddView.as_view(), name="cart_add"),
    path('delete/<str:id>', CartDeleteView.as_view(), name="cart_delete"),
    path('order/add', OrderCreationView.as_view(), name="orderadd"),
    path('order/<int:pk>', OrderDetailView.as_view(), name="order_detail"),
    path('applydiscount/<int:pk>', ApplyDiscountCode.as_view(), name="apply_discount"),
    path('purchase', Purchase.as_view(), name="purchase"),
    # path('sendrequest/<int:pk>', PurchaseView.as_view(), name="send_request"),
]

products/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path('product-detail/<str:title>', views.Product_Detail, name="product_detail"),
    path('category/<str:category_title>/', views.category_product, name='filtered_product_list'),
    path('products', views.product_list, name="product_list"),
    path('search', views.Search, name="search"),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('add_wishlist/<int:id>/', views.add_wishlist, name="add_wishlist"),
    path('go-to-gateway/', views.go_to_gateway_view, name="gateway"),

]

profile_users/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('account/login', views.UserLoginView.as_view(), name="user_login"),
    path('account/logout', views.UserLogOut, name="user_logout"),
    path('account/register', views.UserRegisterView.as_view(), name="user_register"),
    path('account/add/address', views.AddAddressView.as_view(), name="add_address"),
]

cart/models.py
from django.db import models
from django.conf import settings
from products.models import *
from django.utils import timezone


class DiscountCode(models.Model):
    name = models.CharField(max_length=20, unique=True)
    discount = models.SmallIntegerField(default=0)
    quantity = models.SmallIntegerField(default=1)
    expire_date = models.DateField(null=True, blank=True)

    def is_expired(self):
        if self.expire_date is not None:
            return timezone.now().date() > self.expire_date
        return False

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="orders")
    total_price = models.IntegerField(default=0)
    phone = models.CharField(max_length=12)
    created = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)
    discount_codes = models.ManyToManyField(DiscountCode, related_name='orders')

    def __str__(self):
        return self.phone


class Orderitem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="items")
    size = models.CharField(max_length=120)
    color = models.CharField(max_length=120)
    quantity = models.SmallIntegerField()
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.order.phone

cart/views.py
import logging
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .cart_module import Cart
from .models import *
from django.contrib import messages
from django.urls import reverse


class CartDetailView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        cart_qty = len(cart)
        if request.user.is_authenticated:
            products_wish = Product.objects.filter(wishlist=request.user)
            wishlist_count = products_wish.count()
        else:
            # For anonymous users, use session to store wishlist items
            wishlist = request.session.get('wishlist', [])
            wishlist_count = len(wishlist)
        is_cart_empty = cart_qty == 0
        return render(request, 'cart/cart_detail.html',
                      context={'cart': cart, 'cart_qty': cart_qty, 'is_cart_empty': is_cart_empty,
                               'wishlist_count': wishlist_count})


class CartAddView(View):
    def get(self, request):
        cart = Cart(request)
        cart_qty = len(cart)
        if request.user.is_authenticated:
            products_wish = Product.objects.filter(wishlist=request.user)
            wishlist_count = products_wish.count()
        else:
            # For anonymous users, use session to store wishlist items
            wishlist = request.session.get('wishlist', [])
            wishlist_count = len(wishlist)

        return render(request, 'cart/cart_detail.html',
                      context={'cart': cart, 'cart_qty': cart_qty, 'wishlist_count': wishlist_count})

    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        size, color, quantity = request.POST.get("size", "Empty"), request.POST.get("color", "Empty"), request.POST.get(
            "quantity")
        cart = Cart(request)
        cart.add(product, quantity, color, size)
        print(size, color, quantity)
        messages.success(request,
                         f'Product {product.title} added to your cart. <a href="{reverse("cart:cart_detail")}" class="alert-link">Your Cart</a>')
        return redirect("cart:cart_detail")


# Replace 'your_app' with the actual name of your app

class CartDeleteView(View):
    template = 'cart/cart_detail.html'  # Replace with your actual template name

    def get_context_data(self, **kwargs):
        context = {}
        cart = Cart(self.request)
        context['cart_qty'] = len(cart)

        if self.request.user.is_authenticated:
            products_wish = Product.objects.filter(wishlist=self.request.user)
            context['wishlist_count'] = products_wish.count()
        else:
            # For anonymous users, use session to store wishlist items
            wishlist = self.request.session.get('wishlist', [])
            context['wishlist_count'] = len(wishlist)

        return context

    def get(self, request, id):
        cart = Cart(request)
        cart.delete(id)
        messages.success(request, 'Product has been removed')

        # Redirect to the cart detail page with the context
        return render(request, self.template, context=self.get_context_data())


class OrderDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        cart = Cart(request)
        cart_qty = len(cart)
        if request.user.is_authenticated:
            products_wish = Product.objects.filter(wishlist=request.user)
            wishlist_count = products_wish.count()
        else:
            # For anonymous users, use session to store wishlist items
            wishlist = request.session.get('wishlist', [])
            wishlist_count = len(wishlist)
        products_wish = Product.objects.filter(wishlist=request.user)
        wishlist_count = products_wish.count()
        order = get_object_or_404(Order, id=pk)
        return render(request, 'cart/order_detail.html',
                      {'order': order, 'cart_qty': cart_qty, 'wishlist_count': wishlist_count,
                       'wishlist_count': wishlist_count})


class OrderCreationView(LoginRequiredMixin, View):
    def get(get, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user, total_price=cart.total())
        for item in cart:
            Orderitem.objects.create(order=order, product=item['product'], color=item['color'], size=item['size'],
                                     quantity=item['quantity'], price=item['price'])

        cart.remove_cart()
        return redirect('cart:order_detail', order.id)


class ApplyDiscountCode(LoginRequiredMixin, View):
    def get(self, request, pk):
        cart = Cart(request)
        cart_qty = len(cart)
        if request.user.is_authenticated:
            products_wish = Product.objects.filter(wishlist=request.user)
            wishlist_count = products_wish.count()
        else:
            # For anonymous users, use session to store wishlist items
            wishlist = request.session.get('wishlist', [])
            wishlist_count = len(wishlist)
        products_wish = Product.objects.filter(wishlist=request.user)
        wishlist_count = products_wish.count()
        order = get_object_or_404(Order, id=pk)
        return render(request, 'cart/order_detail.html',
                      {'order': order, 'cart_qty': cart_qty, 'wishlist_count': wishlist_count,
                       'wishlist_count': wishlist_count})

    def post(self, request, pk):
        code = request.POST.get('discount_code')
        order = get_object_or_404(Order, id=pk)

        # Check if the discount code has already been used for this order
        if order.discount_codes.filter(name=code).exists():
            return render(request, 'cart/order_detail.html', {
                'order': order,
                'already_used': True,
            })

        discount_code = get_object_or_404(DiscountCode, name=code)

        expired = discount_code.is_expired()
        quantity_finished = discount_code.quantity == 0

        if expired or quantity_finished:
            return render(request, 'cart/order_detail.html', {
                'order': order,
                'expired': expired,
                'quantity_finished': quantity_finished,
            })

        order.total_price -= order.total_price * discount_code.discount / 100
        order.save()
        order.discount_codes.add(discount_code)  # Add the discount code to the order's used discount codes
        discount_code.quantity -= 1
        discount_code.save()  # Decrease the quantity of the discount code
        return redirect('cart:order_detail', order.id)


class Purchase(View):
    def get(self, request):
        cart = Cart(request)
        cart_qty = len(cart)
        if request.user.is_authenticated:
            products_wish = Product.objects.filter(wishlist=request.user)
            wishlist_count = products_wish.count()
        else:
            # For anonymous users, use session to store wishlist items
            wishlist = request.session.get('wishlist', [])
            wishlist_count = len(wishlist)

        user_phone = request.user.phone
        return render(request, 'cart/purchase.html',
                      context={'cart_qty': cart_qty, 'wishlist_count': wishlist_count, 'user_phone': user_phone})

cart/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    {% block cart_quantity %}
        <div id="cart-qty" class="qty">{{ cart_qty }}</div>
    {% endblock %}
    {% block wishlist_count %}
        <div id="wishlist-qty" class="qty">{{ wishlist_count }}</div>
    {% endblock %}

    <!-- SECTION -->
    <div class="section">
        <!-- container -->
        <div class="container">
            {% if messages %}
                <div class="alert alert-success" role="alert">
                    {% for message in messages %}
                        {{ message|safe }}
                    {% endfor %}
                </div>
            {% endif %}
            <!-- row -->
            <div class="row">
                <div class="col-lg-8 table-responsive mb-5">
                    <table class="table table-light table-borderless table-hover text-center mb-0">
                        <thead class="thead-dark">
                        <tr>
                            <th>Images</th>
                            <th>Product Name</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Color</th>
                            <th>Size</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                        </thead>
                        <tbody class="align-middle">
                        {% for item in cart %}
                            <tr>
                                <td class="align-middle"><img src="{{ item.product.image.url }}"
                                                              alt="{{ item.product.title }}" style="width: 50px;"></td>
                                <td class="align-middle">{{ item.product.title }}</td>
                                <td class="align-middle">${{ item.price }}</td>
                                <td class="align-middle"> {{ item.quantity }}</td>
                                <td class="align-middle"> {{ item.color }}</td>
                                <td class="align-middle"> {{ item.size }}</td>
                                <td class="align-middle">${{ item.total }}</td>
                                <td class="align-middle">
                                    <a href="{% url "cart:cart_delete" item.unique_id %}" class="btn btn-sm btn-danger">
                                        <i class="fa fa-times"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="col-lg-4">
                    <div class="bg-light p-4 mb-4">
                        <h5 class="section-title position-relative text-uppercase mb-3">
                            <span class="bg-secondary pr-3">Cart Summary</span>
                        </h5>
                        <div class="d-flex justify-content-between mt-2">
                            <h6>Total</h6>
                            <h6>${{ cart.total }}</h6>
                        </div>

                        {#                        {% if not request.user. %}#}
                        {#                            <a href="{% url "product:product_list" %}" class="btn btn-danger mt-3">#}
                        {#                                find product#}
                        {#                            </a>#}

                        {% if not is_cart_empty %}
                            <a href="{% url "cart:orderadd" %}" class="btn btn-danger mt-3">
                                Proceed To Checkout
                            </a>
                        {% else %}
                            <!-- Optionally, you can display a message or alternative content when the cart is empty -->
                            <h6 class="alert-danger">Your cart is empty. Add some products to proceed to checkout.</h6>
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /SECTION -->

{% endblock %}

cart/templates/cart/order_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    {% block cart_quantity %}
        <div id="cart-qty" class="qty">{{ cart_qty }}</div>
    {% endblock %}
    {% block wishlist_count %}
        <div id="wishlist-qty" class="qty">{{ wishlist_count }}</div>
    {% endblock %}
    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                    <tr>
                        <th>Images</th>
                        <th>Products Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Color</th>
                        <th>Size</th>
                    </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for item in order.items.all %}
                        <tr>
                            <td class="align-middle"><img src="{{ item.product.image.url }}" alt=""
                                                          style="width: 50px;"></td>
                            <td class="align-middle">{{ item.product.title }}</td>
                            <td class="align-middle">${{ item.price }}</td>
                            <td class="align-middle"> {{ item.quantity }}</td>
                            <td class="align-middle"> {{ item.color }}</td>
                            <td class="align-middle"> {{ item.size }}</td
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" method="post" action="{% url 'cart:apply_discount' order.id %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="discount_code" class="form-control border-0 p-4"
                               placeholder="Discount Code">
                        <div class="input-group-append">
                            <button class="btn btn-block btn-warning font-weight-bold my-3 py-3">Apply Discount Code
                            </button>
                        </div>
                    </div>
                    {% if expired %}
                        <p class="text-danger">Discount code has expired.</p>
                    {% endif %}
                    {% if quantity_finished %}
                        <p class="text-danger">Discount code quantity has finished.</p>
                    {% endif %}
                    <p> use 'django' Code to discount 20% </p>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ order.total_price }}</h5>
                        </div>
                        {#                        {% if request.user.addresses.all %}#}
                        {#                            <a href="{% url "cart:orderadd" %}"#}
                        {#                               class="btn btn-block btn-success font-weight-bold my-3 py-3">Pay</a>#}
                        {#                        {% else %}#}
                        {#                            <a class="btn btn-block btn-danger font-weight-bold my-3 py-3">You don't have any address ,#}
                        {#                                Add one</a>#}
                        {#                        {% endif %}#}

                    </div>
                </div>
                {% if request.user.addresses.all %}
                    {#                    <form action="{% url 'cart:send_request' order.id %}" method="post">#}
                    <form action="{% url "cart:purchase" %}" method="get">
                        {% csrf_token %}
                        <select name="address" class="form-control" aria-label="Default select example">
                            {% for address in request.user.addresses.all %}
                                <option value="{{ address.address }}">{{ address.address }}</option>
                            {% endfor %}
                        </select>
                        <a href="{% url "account:add_address" %}?next={% url "cart:order_detail" order.id %}"
                           class="btn btn-block btn-info font-weight-bold my-3 py-3">Add Another Address</a>
                        <button type="submit" class="btn btn-block btn-success font-weight-bold my-3 py-3">Pay</button>
                    </form>
                {% else %}
                    <a href="{% url "account:add_address" %}?next={% url "cart:order_detail" order.id %}"
                       class="btn btn-block btn-info font-weight-bold my-3 py-3">Add Address</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- Cart End -->


{% endblock %}

cart/templates/cart/purchase.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% block cart_quantity %}
        <div id="cart-qty" class="qty">{{ cart_qty }}</div>
    {% endblock %}
    {% block wishlist_count %}
        <div id="wishlist-qty" class="qty">{{ wishlist_count }}</div>
    {% endblock %}

    <!-- SECTION -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-8">
                    <h2 class="alert-success">WELL DONE USER: {{ user_phone }}</h2>
                </div>

            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->

{% endblock %}