ElectoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("home.urls")),
                  path('', include("products.urls")),
                  path('', include("profile_users.urls")),
                  path('', include("contact.urls")),
                  path('cart/', include("cart.urls")),
                  path('accounts/', include("allauth.urls")),
                  # path('bankgateways/', az_bank_gateways_urls()),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('detail/', CartDetailView.as_view(),name="cart_detail"),
    path('add/<int:pk>', CartAddView.as_view(), name="cart_add"),
    path('delete/<str:id>', CartDeleteView.as_view(), name="cart_delete"),
    path('order/add', OrderCreationView.as_view(), name="orderadd"),
    path('order/<int:pk>', OrderDetailView.as_view(), name="order_detail"),
    path('applydiscount/<int:pk>', ApplyDiscountCode.as_view(), name="apply_discount"),
    path('purchase', Purchase.as_view(), name="purchase"),
    # path('sendrequest/<int:pk>', PurchaseView.as_view(), name="send_request"),
]

profile_users/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('account/login', views.UserLoginView.as_view(), name="user_login"),
    path('account/logout', views.UserLogOut, name="user_logout"),
    path('account/register', views.UserRegisterView.as_view(), name="user_register"),
    path('account/add/address', views.AddAddressView.as_view(), name="add_address"),
]

profile_users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class UserManager(BaseUserManager):
    def create_user(self, phone, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not phone:
            raise ValueError("Users must have a phone number")

        user = self.model(
            phone=phone,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            phone,
            password=password
        )
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        null=True,
        blank=True,
        unique=True,
    )
    fullname = models.CharField(max_length=70, verbose_name="full name")
    phone = models.CharField(max_length=12, unique=True, verbose_name="phone number")
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.phone

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    @is_staff.setter
    def is_staff(self, value):
        "Set the user's staff status"
        self.is_admin = value


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="addresses")
    fullname = models.CharField(max_length=50)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=12)
    address = models.CharField(max_length=500)
    postal_code = models.CharField(max_length=30)

    def __str__(self):
        return self.user.phone

profile_users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, SetPasswordForm
from django.core.exceptions import ValidationError
from .models import *
from django.core import validators
from django.core.validators import RegexValidator
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation", widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ('phone',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ("phone", "password", "is_active", "is_admin")


class AddressFormCreation(forms.ModelForm):
    user = forms.IntegerField(required=False)

    class Meta:
        model = Address
        exclude = ('user',)


class UserLoginForm(forms.Form):
    phone = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}),
                            validators=[validators.MaxLengthValidator(11)], label="Phone number:")
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}), label="Your Password:")
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)


class UserRegisterForm(forms.Form):
    phone = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}),
                            validators=[validators.MaxLengthValidator(11)], label="Phone number:")
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}), label="Your Password:")
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

profile_users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import FormView

from products.models import Product
from .forms import *
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from cart.cart_module import Cart


def synchronize_wishlist(request):
    if request.user.is_authenticated:
        # Get the products in the session wishlist
        session_wishlist = request.session.get('wishlist', [])

        # Add products from the session wishlist to the user's wishlist
        for product_id in session_wishlist:
            product = get_object_or_404(Product, id=product_id)
            product.wishlist.add(request.user)

        # Clear the session wishlist after synchronizing with the user's wishlist
        request.session['wishlist'] = []


class UserLoginView(FormView):
    def get(self, request):
        cart = Cart(request)
        cart_qty = len(cart)
        if request.user.is_authenticated:
            products_wish = Product.objects.filter(wishlist=request.user)
            wishlist_count = products_wish.count()
        else:
            # For anonymous users, use session to store wishlist items
            wishlist = request.session.get('wishlist', [])
            wishlist_count = len(wishlist)
        form = UserLoginForm()
        return render(request, "profile_users/user_login.html",
                      context={'form': form, 'cart_qty': cart_qty, 'wishlist_count': wishlist_count})

    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            # Authenticate using the standard username and password fields
            user = authenticate(request, username=cd['phone'], password=cd['password'])

            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in now")
                synchronize_wishlist(request)
                next_page = request.GET.get('next')
                if next_page:
                    return redirect(next_page)
                return redirect('/')
            else:
                form.add_error("phone", "Invalid username or password")
        else:
            form.add_error("phone", "Invalid data")

        return render(request, 'profile_users/user_login.html', {'form': form})


def UserLogOut(request):
    logout(request)
    messages.success(request, "You are logged out now")
    synchronize_wishlist(request)
    return redirect('/')


def is_strong_password(password):
    return password.isalnum() and len(password) >= 8


class UserRegisterView(FormView):
    def get(self, request):
        cart = Cart(request)
        cart_qty = len(cart)
        if request.user.is_authenticated:
            products_wish = Product.objects.filter(wishlist=request.user)
            wishlist_count = products_wish.count()
        else:
            # For anonymous users, use session to store wishlist items
            wishlist = request.session.get('wishlist', [])
            wishlist_count = len(wishlist)
        form = UserRegisterForm()
        return render(request, "profile_users/user_register.html",
                      context={'form': form, 'cart_qty': cart_qty, 'wishlist_count': wishlist_count})

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if User.objects.filter(phone=cd["phone"]).exists():
                form.add_error("phone", "Email or phone number already exists")
            elif not is_strong_password(password=cd["password"]):
                form.add_error("password", "Password must be at least 8 characters long")
            else:
                user = User.objects.create_user(phone=cd["phone"], password=cd["password"])
                authenticated_user = authenticate(request, phone=cd["phone"], password=cd["password"])
                login(request, authenticated_user)
                messages.success(request, "You are logged in now")
                synchronize_wishlist(request)
                return redirect('/')
        else:
            form.add_error("phone", "Invalid data")
        # If there are errors or invalid data, render the registration page
        return render(request, "profile_users/user_register.html", context={'form': form})


class AddAddressView(View):
    def post(self, request):
        form = AddressFormCreation(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()
            next_page = request.GET.get('next')
            if next_page:
                return redirect(next_page)
        return render(request, 'profile_users/add_address.html', {'form': form})

    def get(self, request):
        cart = Cart(request)
        cart_qty = len(cart)
        if request.user.is_authenticated:
            products_wish = Product.objects.filter(wishlist=request.user)
            wishlist_count = products_wish.count()
        else:
            # For anonymous users, use session to store wishlist items
            wishlist = request.session.get('wishlist', [])
            wishlist_count = len(wishlist)
        form = AddressFormCreation()
        return render(request, 'profile_users/add_address.html',
                      {'form': form, 'cart_qty': cart_qty, 'wishlist_count': wishlist_count})

profile_users/templates/profile_users/user_login.html
{% extends "base.html" %}
{% load static %}
{% load socialaccount %}
{% block content %}


    {% block cart_quantity %}
        <div id="cart-qty" class="qty">{{ cart_qty }}</div>
    {% endblock %}
    {% block wishlist_count %}
        <div id="wishlist-qty" class="qty">{{ wishlist_count }}</div>
    {% endblock %}
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12 text-left mb-5">
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-4">
                    <div class="login-wrap p-0">
                        <h3 class="mb-4 text-center"> Do you have an account?</h3>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.phone.label_tag }}
                                {% if form.phone.errors %}
                                    <div class="alert alert-danger">{{ form.phone.errors }}</div>
                                {% endif %}
                                {{ form.phone }}
                            </div>
                            <div class="form-group">
                                {{ form.password.label_tag }}
                                {% if form.password.errors %}
                                    <div class="alert alert-danger">{{ form.password.errors }}</div>
                                {% endif %}
                                <div class="password-toggle">
                                    {{ form.password }}
                                </div>
                            </div>
                            <div class="form-group">
                                {% if form.captcha.errors %}
                                    <div class="alert alert-danger">{{ form.captcha.errors }}</div>
                                {% endif %}
                                {{ form.captcha }}
                            </div>
                            <div class="form-group">
                                <button type="submit" class="primary-btn order-submit">Login</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">Remember Me
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="form-group">
                                     <a href="{% url "account:user_register" %}" >Don't have an
                                    account?</a>
                                </div>
                            </div>
                            <div class="w-100 text-center">
                                <a href="{% url "account:user_register" %}" style="color: #fff">Don't have an
                                    account?</a>
                            </div>
                            {#                            <p class="w-100 text-center mt-3">&mdash; Or Sign In With &mdash;</p>#}
                            {#                            <div class="social d-flex justify-content-center">#}
                            {#                                <a href="{% provider_login_url 'google' %}" class="px-2 py-2 ml-md-1 rounded">#}
                            {#                                    <span class="ion-logo-google mr-2"></span> Google#}
                            {#                                </a>#}
                            {#                            </div>#}
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

profile_users/templates/profile_users/user_register.html
{% extends "base.html" %}
{% load static %}
{% block content %}



    {% block cart_quantity %}
        <div id="cart-qty" class="qty">{{ cart_qty }}</div>
    {% endblock %}
    {% block wishlist_count %}
        <div id="wishlist-qty" class="qty">{{ wishlist_count }}</div>
    {% endblock %}

    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12 text-center mb-5">
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-4">
                    <div class="login-wrap p-0">
                        <h3 class="mb-4 text-center">Don't have an account?</h3>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.phone.label }}
                                {% if form.phone.errors %}
                                    <div class="alert alert-danger">{{ form.phone.errors }}</div>
                                {% endif %}
                                {{ form.phone }}
                            </div>
                            <div class="form-group">
                                {{ form.password.label }}
                                {% if form.password.errors %}
                                    <div class="alert alert-danger">{{ form.password.errors }}</div>
                                {% endif %}
                                {{ form.password }}
                            </div>
                            <div class="form-group">
                                {% if form.captcha.errors %}
                                    <div class="alert alert-danger">{{ form.captcha.errors }}</div>
                                {% endif %}
                                {{ form.captcha }}
                            </div>
                            <div class="form-group">
                                <button type="submit" class="primary-btn order-submit">register</button>
                            </div>
                            <div class="form-group">
                                <a href="{% url "account:user_login" %}" >Do you have an account?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>



{% endblock %}