ElectoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("home.urls")),
                  path('', include("products.urls")),
                  path('', include("profile_users.urls")),
                  path('', include("contact.urls")),
                  path('cart/', include("cart.urls")),
                  path('accounts/', include("allauth.urls")),
                  # path('bankgateways/', az_bank_gateways_urls()),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('detail/', CartDetailView.as_view(),name="cart_detail"),
    path('add/<int:pk>', CartAddView.as_view(), name="cart_add"),
    path('delete/<str:id>', CartDeleteView.as_view(), name="cart_delete"),
    path('order/add', OrderCreationView.as_view(), name="orderadd"),
    path('order/<int:pk>', OrderDetailView.as_view(), name="order_detail"),
    path('applydiscount/<int:pk>', ApplyDiscountCode.as_view(), name="apply_discount"),
    path('purchase', Purchase.as_view(), name="purchase"),
    # path('sendrequest/<int:pk>', PurchaseView.as_view(), name="send_request"),
]

templates/includes/navbar.html
{#<!-- cart_dropdown.html -->#}
{#<div class="cart-dropdown">#}
{#    <div class="cart-list">#}
{#        <div class="product-widget">#}
{#            <div class="product-img">#}
{#                <img src="{{ item.product.image.url }}" alt="">#}
{#            </div>#}
{#            <div class="product-body">#}
{#                <h3 class="product-name"><a href="#">{{ item.product.title }}</a></h3>#}
{#                <h4 class="product-price">#}
{#                    <span class="qty">{{ item.quantity }}x</span>${{ item.discount }}.00#}
{#                </h4>#}
{#            </div>#}
{#            <a href="" class="delete"><i class="fa fa-close"></i></a>#}
{#        </div>#}
{#    </div>#}
{#    <div class="cart-summary">#}
{##}
{#        <h5>TOTAL: ${{ cart.total }}</h5>#}
{#    </div>#}
{#    <div class="cart-btns">#}
{#        <a href="{% url 'cart:cart_detail' %}">View Cart</a>#}
{#        <a href="{% url 'cart:orderadd' %}">Checkout <i class="fa fa-arrow-circle-right"></i></a>#}
{#    </div>#}
{#</div>#}